spring:
  boot:
    admin:
      client:
        url: http://localhost:6060
        username: "admin"
        password: "admin123"
#aplication name        
    application:
        name: employeeService
#server port details        
server:
    port: 7070
#register with eureka    
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
          defaultZone: http://localhost:8888/eureka/